nome = input("Digite o nome da aluna: ")
idade = int(input("Digite a idade da aluna: "))
altura = float(input("Digite a altura da aluna: "))
hobbies = input("Digite os hobbies da aluna: ")
hobbies1 = hobbies.split(",")
endereco_rua = input("Digite o nome da rua da aluna: ")
endereco_num = int(input("Digite o número do endereço da aluna: "))
endereco_cidade = input("Digite a cidade da aluna: ")
endereco = (endereco_rua, endereco_num, endereco_cidade)
email = input("Digite o e-mail da aluna: ")
telefone = input ("Digite o telefone da aluna: ")
contato = {"e-mail": email, "telefone": telefone}

print ("\nOlá, segue informações sobre a aluna:")
print ("Nome:", nome)
print ("Idade:", idade)
print ("Altura:", altura)
print ("Hobbies:", hobbies)
print ("Endereço:", endereco)
print ("Contato:", contato)